site_name: pyrad2
theme:
  name: material
  features:
    - content.code.copy
    - navigation.expand
    
nav:
  - Home: index.md
  - Getting Started:
    - Setup and Concepts: setup.md
    - Running a RADIUS Server: server.md
    - Making RADIUS Requests: client.md
  - Releases: releases.md
  - Pyrad Compatibility : compatibility.md
  - API Reference:
      - server: api/server.md
      - server_async: api/server_async.md
      - client: api/client.md
      - client_async: api/client_async.md
      - radsec:
        - Server: api/radsec_server.md
        - Client: api/radsec_client.md
      - packet: api/packet.md
      - dictionary: api/dictionary.md
      - host: api/host.md
      - utils: api/utils.md
      - dictfile: api/dictfile.md
      - proxy: api/proxy.md
      - bidict: api/bidict.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            members_order: source